variable "env" {}
variable "cluster_name" {}
variable "eks_version" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "zone1" {}
variable "zone2" {}
variable "zone3" {}
variable "vpc_cidr" {}
